# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
