# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
