# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='apt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='private_bath',
            field=models.CharField(max_length=255),
        ),
    ]
