# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20171026_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat_position',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='long_position',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
