# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20171026_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='apt_number',
        ),
    ]
