# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_place_apt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='geocode',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat_position',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='long_position',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
    ]
